"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

# Render will provide the production SECRET_KEY.
# The fallback keeps your local project working.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-a&l$kn9g6z3$s^yg3i0zwffaryl8g6lom-&jg700w&wv5!rxpm'
)

# DEBUG=False in production.
# You can still use DEBUG=True locally by setting the environment variable.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Render will provide your public hostname through ALLOWED_HOSTS.
# The fallback keeps local development working.
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1'
).split(',')


# Authentication redirect targets.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps:
    'accounts',
    'records',
    'reports',

    # create categories by default
    'categories.apps.CategoriesConfig',

    # custom translation module + tag library
    'core.apps.CoreConfig',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise serves static files on Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',

                # Exposes the user's currency + notification preferences.
                'core.context_processors.ui_preferences',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

# Local:
#     SQLite (db.sqlite3)
#
# Render:
#     PostgreSQL through DATABASE_URL

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Supported languages
# English, Chinese, Amazigh, Arabic, French
LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', '中文'),
    ('ber', 'ⵜⴰⵎⴰⵣⵉⵖⵜ (Amazigh)'),
    ('ar', 'العربية'),
    ('fr', 'Français'),
]


# ============================================================
# STATIC FILES
# ============================================================

STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_URL = 'static/'

# Required for collectstatic on Render.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise compression/storage.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# AVATAR UPLOAD CONSTRAINTS
# ============================================================

MAX_UPLOAD_SIZE = 5 * 1024 * 1024  # 5 MB