# Generated by Django 6.0.4 on 2026-09-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
